Wrote 15 unit tests for 9 models using `django.test` package, Created an API endpoint for fetching a unique comment for a particular article
m2b3/SciCommons-backend pull request #12
Opened 2024-03-17 20:22 UTC by dinakar17

![unittests](https://github.com/m2b3/SciCommons-backend/assets/85105044/d5837160-5cf5-4c84-9dc4-067676424801)

One Unit Test failure suggests that the expected exception is not being raised when trying to create another admin for the same community.

Created an API endpoint for fetching one comment (review) about a specific article. The objective is to use this to create a shareable URL link for each comment for SEO purposes.
![image](https://github.com/m2b3/SciCommons-backend/assets/85105044/0cb8d001-2156-41e5-a817-34223cbea555)

2024-03-17 22:53 UTC, JyothiSwaroopReddy07 requested changes

2024-03-17 22:53 UTC, JyothiSwaroopReddy07 commented on app/views.py
> +    @action(methods=['get'], detail=True, url_path='comment/(?P<comment_id>.+)', permission_classes=[ArticlePermission])
This function is not needed for now. As I have implemented the already implemented. Please dont include this function

2024-03-17 22:53 UTC, JyothiSwaroopReddy07 commented on app/tests/test_models.py
> +    def test_unique_admin_per_community(self):
Each community can have more than one admin. Please remove the intented exception error. The testcase works then

2024-03-18 09:51 UTC, sushmanthreddy commented
@dinakar17 can u remove all cache files?

use .gitignore to remove them ,pls remove untracked files..

2024-03-18 15:19 UTC, JyothiSwaroopReddy07 commented
Can also make a git pull to add some changes to which are already present in backend

2024-03-18 15:50 UTC, dinakar17 commented
I've synced both the main branches of the projects.

![image](https://github.com/m2b3/SciCommons-backend/assets/85105044/55f98437-90cc-462e-9e72-4ce8d5aab43c)

2024-03-18 20:46 UTC, JyothiSwaroopReddy07 approved these changes

2024-03-18 21:51 UTC, merged

2024-03-18 21:54 UTC, JyothiSwaroopReddy07 commented
done merged it. thanks for your work